---
- name: setup prometheus
  hosts: localhost
  become: true
  become_method: sudo

  tasks:
  - name: build prometheus image
    docker_image:
      path: "prometheus-dockerfile"
      tag: "1.0"
      name: "prometheus-image"
...