---
- name: setup prometheus
  hosts: localhost
  become: true
  become_method: sudo

  vars:
    root_path: "."
    setup_folder: "{{ root_path }}/setup"
  tasks:
  - name: prepare the folder to download the release code of prometheus
    file:
      path: "{{ setup_folder }}"
      state: directory

  - name: download the prometheus release code
    get_url:
      url: "https://github.com/prometheus/prometheus/releases/download/v1.7.1/prometheus-1.7.1.linux-amd64.tar.gz"
      dest: "{{ setup_folder }}"

...